INSERT INTO manufacture
VALUES
(NULL, 'Татхимпрепараты', 1),
(NULL, 'Боримед', 2),
(NULL, 'ГласкоСмитКляйн', 4 ),
(NULL, 'Pliva Hrvatska', 13),
(NULL, 'Эллара', 1),
(NULL, 'ЭббВ', 12),
(NULL, 'Бурлин-хеми', 4),
(NULL, 'Unipharm', 10),
(NULL, 'B-МИН ООО', 1),
(NULL, 'A&D', 9),
(NULL, 'OMRON', 9),
(NULL, 'LifeScan', 10),
(NULL, 'ФастКликс', 4),
(NULL, 'Littel Doctor', 8),
(NULL, 'Luer', 8),
(NULL, 'MicroLife', 7),
(NULL, 'Nutrison', 6),
(NULL, 'ТОО Леовит', 1),
(NULL, 'Пропеллер', 2),
(NULL, 'Vichy', 5),
(NULL, 'La Roche', 5),
(NULL, 'Красногорсклек', 1),
(NULL, 'Дельта Медикал', 5),
(NULL, 'Бфйер Веймар', 4);